/** All possible equipment types from the exercise catalog. */
export const ALL_EQUIPMENT = [
  { id: 'barbell', label: 'Barras y Discos' },
  { id: 'dumbbell', label: 'Mancuernas' },
  { id: 'cable', label: 'Poleas y Cables' },
  { id: 'smith machine', label: 'Máquina Smith' },
  { id: 'leverage machine', label: 'Máquinas de Palancas' },
  { id: 'body weight', label: 'Peso Corporal' },
  { id: 'assisted', label: 'Máquina Asistida' },
  { id: 'ez barbell', label: 'Barra Z' },
  { id: 'band', label: 'Bandas Elásticas' },
  { id: 'kettlebell', label: 'Pesas Rusas' },
  { id: 'medicine ball', label: 'Balón Medicinal' },
  { id: 'stability ball', label: 'Pelota de Estabilidad' },
  { id: 'roller', label: 'Rodillo' },
  { id: 'rope', label: 'Cuerda' },
  { id: 'weighted', label: 'Lastrado' },
  { id: 'bosu ball', label: 'Bosu Ball' },
  { id: 'skierg machine', label: 'SkiErg' },
  { id: 'elliptical machine', label: 'Elíptica' },
  { id: 'stationary bike', label: 'Bicicleta Fija' },
  { id: 'upper body ergometer', label: 'Ergómetro Superior' },
  { id: 'tire', label: 'Neumático' },
  { id: 'trap bar', label: 'Barra Trampa' },
  { id: 'hammer', label: 'Martillo' },
  { id: 'sled machine', label: 'Trineo' },
] as const;
