import type { ThemeConfig, ExerciseItem, ActiveExercise } from './types';

export const THEME_CONFIGS: ThemeConfig[] = [
  {
    id: 'clay-indigo',
    name: '1. Clay Indigo & Peach',
    subtitle: 'Soft Neumorphism & Tactile Clay Cards',
    sampleImage: 'bbae999223e85e11158c0208bb145087.jpg',
    tagline: 'Deep indigo background with warm peach/cream floating soft clay surfaces and pill sliders.',
    bg: '#252243',
    cardBg: '#fce3b8',
    accent: '#ffb562',
    textColor: '#ffffff',
    structuralPrinciple: 'Tactile ticket-stub + horizontal story rail. Extruded/recessed surfaces, dotted dividers, clay avatar bubbles.',
  },
  {
    id: 'warm-latte',
    name: '2. Warm Latte Minimal',
    subtitle: 'Monochromatic Earthy Tone & Oversized Type',
    sampleImage: 'coffeejpg.jpg',
    tagline: 'Warm cappuccino brown, soft latte cream, high-contrast typography, and floating rounded pill cards.',
    bg: '#755439',
    cardBg: '#e6decb',
    accent: '#3e2918',
    textColor: '#3d2918',
    structuralPrinciple: '60/40 magazine spread + bottom sheet. Serif headlines, issue-number framing, circular bezel dial.',
  },
  {
    id: 'dark-stealth',
    name: '3. Ultra Stealth Dark',
    subtitle: 'Minimalist iOS Fitness & Grid Calendar',
    sampleImage: 'dropset.jpg',
    tagline: 'Pure pitch black background (#0d0d0f), charcoal cards (#1b1b20), dot matrix calendar, and bold white metrics.',
    bg: '#0d0d0f',
    cardBg: '#1c1c22',
    accent: '#ffffff',
    textColor: '#ffffff',
    structuralPrinciple: 'Asymmetric grid + dot-matrix calendar. High density, zero chrome, negative-space zones only.',
  },
  {
    id: 'tactile-amber',
    name: '4. Tactical Black & Amber',
    subtitle: 'Glassmorphism & High-Contrast Orange Accent',
    sampleImage: 'logisticjpg.jpg',
    tagline: 'Matte charcoal backdrop (#141519), glowing vibrant amber buttons (#ff6000), dark frosted glass cards.',
    bg: '#141519',
    cardBg: '#21242b',
    accent: '#ff6000',
    textColor: '#ffffff',
    structuralPrinciple: 'Timeline stepper + frosted glass tiles. Translucent layers, amber-only accents, attached badge CTAs.',
  },
  {
    id: 'swiss-brutalist',
    name: '5. Swiss High-Contrast',
    subtitle: 'Heavy Uppercase Typography & Stark Borders',
    sampleImage: 'malendarjpg.jpg',
    tagline: 'Bold uppercase Helvetica headers (MONDAY, EXERCISES), ultra-clean borders, high contrast strike-through tasks.',
    bg: '#1a1a1a',
    cardBg: '#262626',
    accent: '#ff3b00',
    textColor: '#f5f5f5',
    structuralPrinciple: 'Stacked day-accordions + square checklist. Zero radius, zero shadows, 2px black borders, all-caps Helvetica.',
  },
  {
    id: 'neumorphic-slate',
    name: '6. Tactile Neumorphic Slate',
    subtitle: 'Extruded 3D Surfaces & Glowing Ember Controls',
    sampleImage: 'playerjpg.jpg',
    tagline: 'Dark slate gray (#1e2228), dual soft shadows creating 3D tactile buttons, and glowing circular play/timer accents.',
    bg: '#1e2228',
    cardBg: '#242930',
    accent: '#ff4f00',
    textColor: '#e1e7ed',
    structuralPrinciple: 'Single hero dial + recessed wells. Extruded/recessed binary, ember glow focal point per screen.',
  },
  {
    id: 'list-first',
    name: '7. Minimalist List-First',
    subtitle: 'Pure Typeset List & Generous Whitespace',
    sampleImage: 'coffeejpg.jpg',
    tagline: 'No cards, no shadows, no borders — just type, hairline dividers, and space. Icons only in the app header.',
    bg: '#FAFAFA',
    cardBg: '#FFFFFF',
    accent: '#3B82F6',
    textColor: '#111111',
    structuralPrinciple: 'Pure typeset list, almost no chrome. No cards, no shadows, no borders — just type, hairline dividers, and space.',
  },
  {
    id: 'gamified',
    name: '8. Gamified Playful',
    subtitle: 'Progress Rings, Streaks & Badge Grid',
    sampleImage: 'playerjpg.jpg',
    tagline: 'Bright saturated colors, animated progress rings, streak counters, achievement badges, and bouncy pill buttons.',
    bg: '#1E1B4B',
    cardBg: '#312E81',
    accent: '#A855F7',
    textColor: '#FFFFFF',
    structuralPrinciple: 'Progress rings + streak banner + badge grid. Bright saturated colors, rounded everything, celebratory micro-interactions.',
  },
  {
    id: 'retro',
    name: '9. Retro Skeuomorphic',
    subtitle: 'Chalkboard & Notebook Paper Metaphors',
    sampleImage: 'dropset.jpg',
    tagline: 'Physical textures — green chalkboard slate, cream notebook paper, handwritten ink, taped-on index cards.',
    bg: '#1E3A2F',
    cardBg: '#FFF8E7',
    accent: '#1E40AF',
    textColor: '#F5F5DC',
    structuralPrinciple: 'Locker-room chalkboard + notebook paper. Physical metaphors throughout — chalkboard, paper, tape, ink, chalk.',
  },
  {
    id: 'bento-grid',
    name: '10. Bento Grid',
    subtitle: 'Varied-Size Widget Tiles in Grid',
    sampleImage: 'logisticjpg.jpg',
    tagline: 'iOS-style widget grid — mixed tile sizes (1x1, 2x1, 1x2, 2x2), each a self-contained widget with its own micro-layout.',
    bg: '#F4F4F6',
    cardBg: '#FFFFFF',
    accent: '#4F46E5',
    textColor: '#1F2937',
    structuralPrinciple: 'Varied-size widget tiles in a grid. No vertical stacking of full-width sections — everything is a grid tile.',
  },
];

export const INITIAL_EXERCISES: ExerciseItem[] = [
  { id: '1', name: 'Barbell Bench Press', category: 'Chest', muscle: 'Pectorals, Triceps', equipment: 'Barbell', difficulty: 'Intermediate' },
  { id: '2', name: 'Incline Dumbbell Press', category: 'Chest', muscle: 'Upper Chest, Deltoids', equipment: 'Dumbbells', difficulty: 'Intermediate' },
  { id: '3', name: 'Lat Pulldown', category: 'Back', muscle: 'Latissimus Dorsi, Biceps', equipment: 'Cable', difficulty: 'Beginner' },
  { id: '4', name: 'Barbell Back Squat', category: 'Legs', muscle: 'Quadriceps, Glutes', equipment: 'Barbell', difficulty: 'Advanced' },
  { id: '5', name: 'Romanian Deadlift', category: 'Hamstrings', muscle: 'Hamstrings, Glutes', equipment: 'Barbell', difficulty: 'Intermediate' },
  { id: '6', name: 'Overhead Shoulder Press', category: 'Shoulders', muscle: 'Deltoids, Triceps', equipment: 'Barbell', difficulty: 'Intermediate' },
  { id: '7', name: 'Cable Lateral Raise', category: 'Shoulders', muscle: 'Lateral Deltoids', equipment: 'Cable', difficulty: 'Beginner' },
  { id: '8', name: 'Tricep Rope Pushdown', category: 'Arms', muscle: 'Triceps', equipment: 'Cable', difficulty: 'Beginner' },
  { id: '9', name: 'Barbell Bicep Curl', category: 'Arms', muscle: 'Biceps', equipment: 'Barbell', difficulty: 'Beginner' },
  { id: '10', name: 'Hanging Leg Raise', category: 'Core', muscle: 'Abs, Hip Flexors', equipment: 'Bodyweight', difficulty: 'Intermediate' },
];

export const INITIAL_ACTIVE_SESSION: ActiveExercise[] = [
  {
    id: 'ex1',
    name: 'Barbell Bench Press',
    muscle: 'Chest',
    sets: [
      { id: 's1', setNum: 1, weightKg: 80, reps: 10, completed: true },
      { id: 's2', setNum: 2, weightKg: 85, reps: 8, completed: true },
      { id: 's3', setNum: 3, weightKg: 90, reps: 6, completed: false },
    ],
  },
  {
    id: 'ex2',
    name: 'Incline Dumbbell Press',
    muscle: 'Upper Chest',
    sets: [
      { id: 's4', setNum: 1, weightKg: 30, reps: 10, completed: true },
      { id: 's5', setNum: 2, weightKg: 32, reps: 8, completed: false },
    ],
  },
];
