import React from 'react';
import { MARK_COLOURS, MARK_GEOMETRY, MARK_PLATE_RADIUS } from './markGeometry';

/**
 * The MorphIQ mark: an abstract body reduced to three shapes.
 *
 * Shoulders, torso, legs — the same taper as the body map on the Library screen,
 * stripped to what still reads at 24px in a launcher. The torso carries the clay
 * accent because it is the one shape the eye lands on first.
 *
 * Geometry lives in `markGeometry.ts` so the icon-generation script shares it.
 */
export const AppMark: React.FC<{
  size?: number;
  /** `icon` paints the sand plate behind the figure; `mark` is transparent. */
  variant?: 'icon' | 'mark';
  className?: string;
  title?: string;
  /** Tags each shape so the splash can animate them in one at a time. */
  animated?: boolean;
}> = ({ size = 48, variant = 'icon', className, title, animated = false }) => {
  const g = MARK_GEOMETRY;

  /**
   * The launcher plate is a fixed asset — it is generated by a Node script with
   * no stylesheet, and an installed icon cannot follow the app's theme anyway,
   * so `icon` keeps the literal palette. The in-app `mark` takes its colour from
   * the tokens instead: painted with the literal cocoa it was a near-black
   * figure on a near-black page in dark mode, which is why the splash looked
   * empty.
   */
  const cocoa = variant === 'icon' ? MARK_COLOURS.cocoa : 'var(--cocoa, #2c241d)';
  const clay = variant === 'icon' ? MARK_COLOURS.clay : 'var(--clay, #c4643c)';

  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 64 64"
      className={className}
      role={title ? 'img' : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
    >
      {variant === 'icon' && (
        <rect x="0" y="0" width="64" height="64" rx={MARK_PLATE_RADIUS} fill={MARK_COLOURS.sand} />
      )}
      <rect {...g.shoulders} fill={cocoa} data-piece={animated ? 'shoulders' : undefined} />
      <rect {...g.torso} fill={clay} data-piece={animated ? 'torso' : undefined} />
      <rect {...g.legLeft} fill={cocoa} data-piece={animated ? 'leg-left' : undefined} />
      <rect {...g.legRight} fill={cocoa} data-piece={animated ? 'leg-right' : undefined} />
    </svg>
  );
};
