-- Who is training right now.
--
-- One row per profile, upserted. Not a log: nobody asks what your presence was
-- twenty minutes ago, and keeping history here would quietly build a second,
-- weaker copy of `workout_logs` that nothing validates.
--
-- **The privacy contract is the shape of this table.** There is no weight column
-- and no reps column, so a partner cannot be shown your loads by any query
-- anyone writes later, including by accident. What a partner may see is the
-- exercise you are on, how far through it you are, and how long you have been
-- going — and that list is exhaustive because these are the only columns.
--
-- This is a lossy, one-way projection of the live session. It is written from
-- the client and never read back into it: `activeSession` still lives only in
-- memory and is still lost if the app dies mid-workout. Reading this back to
-- "restore" a session would turn a presence table into a half-built crash
-- recovery system with none of the guarantees, so it does not happen.

CREATE TABLE IF NOT EXISTS live_sessions (
  "profileId" TEXT PRIMARY KEY,
  -- Generated by the client when a session starts, so an app restart is a new
  -- session rather than the resurrection of the old one. Matters because the
  -- row outlives the client that wrote it.
  "sessionKey" TEXT NOT NULL,
  "startedAt" TIMESTAMPTZ NOT NULL,
  "exerciseName" TEXT,
  "exerciseIndex" INTEGER,
  "exerciseCount" INTEGER,
  "setNumber" INTEGER,
  "setCount" INTEGER,
  "setsDone" INTEGER NOT NULL DEFAULT 0,
  "setsPlanned" INTEGER NOT NULL DEFAULT 0,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "endedAt" TIMESTAMPTZ
);

-- Every read is "who visible to me is live", which filters on freshness.
CREATE INDEX IF NOT EXISTS live_sessions_updated_idx ON live_sessions("updatedAt");
